### ISSUE TITLE
Add default option for boolean values

### ISSUE THREAD

**Issue by darkdragon-001** [docopt/docopt#365]
Declaration

    Usage:
        script.py [optios]
    
    Options:
        --show  Show result [Default: True]

Usage

    opt = docopt(__doc__)
    opt_show = opt['--show']

But `opt_show` is still false called without options...

**Comment by TylerTemp** [comment]
your `--show` does not accept argument. `default` means default value of *argument*, so it wont work.

```
Usage:
  script.py [options]  # not optios

Options:
  --show <true_or_false>  Show result[default: True]
```

can do

**Comment by goodmami** [comment]
@TylerTemp is right, but the default value of his solution is the string `"True"` and not the boolean value `True`. Simple options without arguments default to `True` when they are used and `False` when they are optional and not used. If the option can be repeated, however, they default to an integer value that counts the number of occurrences. Since the default of such a count is 0, it also evaluates to False when not used:

```
Usage:
  script.py [options] [-v...]
Options:
  --show    show result
  -v        increase verbosity
```

```sh
$ script.py
# {'--show': False, '-v': 0}
$ script.py --show -vvv
# {'--show': True, '-v': 3}
```

If you want to change the semantics so the default behavior is to, e.g., show the result and using the option hides it, change your option name:

```
Usage:
  script.py [options]
Options:
  --hide    don't show result
```

Then your script would do something like:

```python
if not args['--hide']:
    show(result)
```

**Comment by darkdragon-001** [comment]
@goodmami Thanks for your clarification and workaround!

**Comment by goodmami** [comment]
@darkdragon-001 I'm glad that worked for you.
I think you can close the issue since you opened it, or an official owner/collaborator could. I cannot as I'm not listed as a collaborator.
