### ISSUE TITLE
repeating arguments can be split by flags, leading to non-intuitive results

### ISSUE THREAD

**Issue by JosephSummerhays1** [docopt/docopt#496]
```
(base) svw@jewel-8:~$ cat test.py 
"""Usage: test.py <first>... [--second=PARAM...]

"""
from docopt import docopt
print(docopt(__doc__))
(base) svw@jewel-8:~$ python3 test.py 1 2 3 --second 4 5 6
{'--second': ['4'],
 '<first>': ['1', '2', '3', '5', '6']}
```

consider the above case. The ellipsis at the end of `PARAM `isn't intuitive, because without reading the docs or experimenting I can't know whether it applies to `PARAM` or `--second=PARAM`. No matter though, testing reveals it to be the latter. The real problem is, the `5` and `6` are becoming part of `<first>`, which is extremely non-intuitive. I would assume that elements parse as part of `<first>...` can't be split by other arguments. In no other area I am aware of, can ellipses be split like this.

In my mind there can only be one of two valid solution. Either the command `python3 test.py 1 2 3 --second 4 5 6` shouldn't parse, or `5` and `6` should become part of `--second`. I suspect the former, since that is more in keeping with the observed behavior mentioned above.

**Comment by Sylvain303** [comment]
Hi @JosephSummerhays1 

In the world of command line parsing, there's no such thing as multiples values for a single named argument `--second=`. It's based on the nature of the shell that splits every argument on spaces.

So named argument receives its associated single argument. For fancier behavior some argument parser allow to split it in two `--myarg value` the shell will pass two argument: `--myarg` and `value`. The lib (here docopt) will associated the second argument with the named argument for convenience. 

In such case where you would like to pass multiple value to a single named argument you will find something like: `--second="1,2,3,4"`  or `--second="1 2 3 4"` or you most commonly have to repeat `-v /lovcalpath:/data` `-v /some/where/else:/data2`

It could be confusing I agree, but that's the nature of the shell parsing first then transiting argument, then the lib doing it's magic (more or less). Also docopt is based on POSIX argument parsing (I think [this one](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html)).

Hope that it will help you in your command line parsing journey. :wink:

**Comment by JosephSummerhays1** [comment]
Thanks, but you only address the peripheral concern. The main concern is that the values being listed in `<first>` are being split by `--second`. How does it make sense that `5` and `6` would be part of `<first>` when they come after second?

**Comment by Sylvain303** [comment]
@JosephSummerhays1,

You can see in your example: `<first>...` as a collector for multiple argument and `--second=PARAM...` as a repeatable named argument, also known as `Option`.

docopt, when it receives the argument from `sys.argv` try to match one of the possibly rules of the parsed `__doc__`.

So given that named argument can receive at most one argument: `4`, the `5` and `6` are then also assigned to `<first>` as the argument order is not enforced.

> `options_first`, by default `False`. If set to True will disallow mixing options and positional argument. I.e. after first positional argument, all arguments will be interpreted as positional even if the look like options. This can be used for strict compatibility with POSIX, or if you want to dispatch your arguments to other programs

Note that setting `options_first` at `True` will not help, because the `--second` will only be recognized in this case if used at the beginning (option first: option what I also name `named argument`, came first) or they will be assigned as an argument.

But I agree with your non-intuitive feeling. Command line parsing has a long history, docopt uses this as a background. The docopt parser also has some annoying behavior, that should be improved. As helping to understand the parsing behavior for example. This lib was really innovative in the way of handling help message as the code for driving the parser. It assumes than you know about command line commonly accepted usage. Sadly [the maintainer of this version fade away](https://github.com/docopt/docopt/issues/371). This can still be used, but some real effort must sometime be done, for understanding the original intended behavior.

The documentation is both on:

https://github.com/docopt/docopt
http://docopt.org/

one active fork is: https://github.com/jazzband/docopt-ng

To achieve what you're expecting, given the `Usage:` you provided:

```
test.py 1 2 3 --second 4 --second 5 --second 6
```

Hope that helps.

**Comment by JosephSummerhays1** [comment]
I see. You're right. Thanks for the help.
