### ISSUE TITLE
[FeatureRequest] Allow hash comments in docstring ?

### ISSUE THREAD

**Issue by shouldsee** [docopt/docopt#505]
Thanks for the great package!

Is there an official way to parse comments in docstring? Currently I am using an ugly one-liner 
like the following, which may 
not be portable for different line-ending.

```python
__doc__=f'''
Usage:
#  my_program command --option <argument>
  {prog} [<optional-argument>]
  {prog} --another-option=<with-argument>
  {prog} (--either-that-option | <or-this-argument>)
  {prog} <repeating-argument> <repeating-argument>...
'''
__doc__ = '\n'.join([x for x in __doc__.splitlines() if not x.strip().startswith('#') ]
from docopt import docopt
args = docopt(__doc__)


```

**Comment by Sylvain303** [comment]
`__doc__` is autopopulated by python. See: https://peps.python.org/pep-0257/

Use your own string instead: :wink: 

```python
from docopt import docopt

prog = 'mysuper_prog'

my_doc = f'''
Usage:
  {prog} command --option <argument>
  {prog} [<optional-argument>]
  {prog} --another-option=<with-argument>
  {prog} (--either-that-option | <or-this-argument>)
  {prog} <repeating-argument> <repeating-argument>...
'''

args = docopt(my_doc)

print(args)
```

outputs:

```
sylvain@lap43: ~$ python t.py 
{'--another-option': None,
 '--either-that-option': False,
 '--option': False,
 '<argument>': None,
 '<optional-argument>': None,
 '<or-this-argument>': None,
 '<repeating-argument>': [],
 'command': False}
```

auto help:

```
sylvain@lap43: ~$ python t.py -h
Usage:
  mysuper_prog command --option <argument>
  mysuper_prog [<optional-argument>]
  mysuper_prog --another-option=<with-argument>
  mysuper_prog (--either-that-option | <or-this-argument>)
  mysuper_prog <repeating-argument> <repeating-argument>...
```

**Comment by shouldsee** [comment]
Thanks. I understand you are suggesting to put comments outside of usage block right?

**Comment by Sylvain303** [comment]
I may have answered too fast, but basically yes. `docopt` principle is to self document the option description and parse it to generate your command parser. Did you saw the video plus the [docopt.org](http://docopt.org/) ?

If the comment is for the developer only, yes put it outside the help string. As the `helpstring` or `docstring` you give in input to `docopt` is parsed and don't support comment, and in also returned more or less verbatim to the user on `-h`.

If the `docopt` input is becoming very complex and hit `docopt` limitation it's another story.

By design `docopt` was though to be very simple with little to remember about the parsing and it do all of you, except calling callback, as you may have seen in other lib.

Unfortunately the main python project is stalled by its original maintainer , without giving hand to anyone else.

https://github.com/docopt/docopt/issues/371

Another fork exists for python: https://github.com/bazaar-projects/docopt-ng

**Comment by shouldsee** [comment]
> I may have answered too fast, but basically yes. `docopt` principle is to self document the option description and parse it to generate your command parser. Did you saw the video plus the [docopt.org](http://docopt.org/) ?
> 
> If the comment is for the developer only, yes put it outside the help string. As the `helpstring` or `docstring` you give in input to `docopt` is parsed and don't support comment, and is also returned more or less verbatim to the user on `-h`.
> 
> If the `docopt` input is becoming very complex and hit `docopt` limitation it's another story.
> 
> By design `docopt` was though to be very simple with little to remember about the parsing and it do all of you, except calling callback, as you may have seen in other lib.
> 
> Unfortunately the main python project is stalled by its original maintainer , without giving hand to anyone else.
> 
> #371
> 
> Another fork exists for python: https://github.com/bazaar-projects/docopt-ng

Great! Thanks for the pointers! I found the idea quite powerful with possible improvements. Might PR to the fork :D
